name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  github-pages-deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Run deploy script
        run: |
          git config user.name ${{ secrets.USERNAME }} && git config user.email ${{ secrets.EMAIL }}
          git checkout --orphan gh-pages
          npm run build
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
